export enum ApiErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  DUPLICATE_DOCUMENT = 'DUPLICATE_DOCUMENT',
  DOCUMENT_INVALID = 'DOCUMENT_INVALID',
  PROVEEDOR_NOT_FOUND = 'PROVEEDOR_NOT_FOUND',
  CLIENTE_NOT_FOUND = 'CLIENTE_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
